site_name: abcdef
site_author: Marcin
copyright: C
repo_url: https://example.pl
edit_uri: https://example.pl/edit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - smarty
  - attr_list

plugins:
  - search
  - print-site:
      add_to_navigation: true
      add_full_urls: false
      add_table_of_contents: true
      toc_title: "Table of Contents"
      toc_depth: 2
      enumerate_headings: true
      enumerate_figures: true
      # add_cover_page: true
      path_to_pdf: "assets/site.pdf"

